In [6]:
import pickle
import pandas as pd
from pathlib import Path

def load_reference_db(file_path: str | Path) -> pd.DataFrame | None:
    """
    人事異動リファレンスDBのpickleファイルを読み込む関数
    
    Parameters:
        file_path (str): pickleファイルのパス
        
    Returns:
        pd.DataFrame: 人事異動リファレンスDBのデータ
        
    Raises:
        FileNotFoundError: 指定されたファイルが存在しない場合
        pickle.UnpicklingError: pickleファイルの読み込みに失敗した場合
        EOFError: ファイルの読み込み中に予期せずファイルの終わりに達した場合
        pickle.PickleError: pickleファイルのフォーマットが不正な場合
    """
    file_path = Path(file_path)
    try:
        #with open(file_path, 'rb') as f:
        with file_path.open('rb') as f:
            df = pickle.load(f)
        return df
    except FileNotFoundError as e:
        print(f"Error: File not found - {file_path}")
        raise e
    except (pickle.UnpicklingError, EOFError, pickle.PickleError) as e:
        print(f"Error: Failed to unpickle the file - {file_path}")
        raise e

In [7]:
df = load_reference_db('reference_db.pickle')
df

,BPR部店コード,BPR部店名,BPR課Grコード,BPR課Gr名,人事部店コード,人事部店名,人事課Grコード,人事課Gr名,エリア部店コード,エリア部店名,...,エリアコード,エリア名称,常駐部店コード,常駐部店名称,Global Address List用設定値1,Global Address List用設定値2,Exchange Server用設定値1,Exchange Server用設定値2,ネットワークドライブ用設定値1,ネットワークドライブ用設定値2
0,1000,本店,1002,融資部,1000,本店,1002,融資部,1000,本店,...,,,,,value_1000_1002_1,value_1000_1002_2,value_1000_1002_1,value_1000_1002_2,value_1000_1002_1,value_1000_1002_2
1,2000,ローン推進部,1002,融資部,2000,ローン推進部,1002,融資部,2000,ローン推進部,...,,,,,value_2000_1002_1,value_2000_1002_2,value_2000_1002_1,value_2000_1002_2,value_2000_1002_1,value_2000_1002_2
2,1000,本店,1002,融資部,1000,本店,1002,融資部,1000,本店,...,,,,,value_1000_1002_1,value_1000_1002_2,value_1000_1002_1,value_1000_1002_2,value_1000_1002_1,value_1000_1002_2
3,1000,本店,1004,人事部,1000,本店,1004,人事部,1000,本店,...,,,,,value_1000_1004_1,value_1000_1004_2,value_1000_1004_1,value_1000_1004_2,value_1000_1004_1,value_1000_1004_2
4,6000,銀行本部,1003,企画部,6000,銀行本部,1003,企画部,6000,銀行本部,...,,,,,value_6000_1003_1,value_6000_1003_2,value_6000_1003_1,value_6000_1003_2,value_6000_1003_1,value_6000_1003_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2000,ローン推進部,1004,人事部,2000,ローン推進部,1004,人事部,2000,ローン推進部,...,,,,,value_2000_1004_1,value_2000_1004_2,value_2000_1004_1,value_2000_1004_2,value_2000_1004_1,value_2000_1004_2
96,3000,海外支店,1001,営業部,3000,海外支店,1001,営業部,3000,海外支店,...,,,,,value_3000_1001_1,value_3000_1001_2,value_3000_1001_1,value_3000_1001_2,value_3000_1001_1,value_3000_1001_2
97,1100,法人営業部,1003,企画部,1100,法人営業部,1003,企画部,1100,法人営業部,...,,,,,value_1100_1003_1,value_1100_1003_2,value_1100_1003_1,value_1100_1003_2,value_1100_1003_1,value_1100_1003_2
98,3000,海外支店,1003,企画部,3000,海外支店,1003,企画部,3000,海外支店,...,,,,,value_3000_1003_1,value_3000_1003_2,value_3000_1003_1,value_3000_1003_2,value_3000_1003_1,value_3000_1003_2
99,1000,本店,1001,営業部,1000,本店,1001,営業部,1000,本店,...,,,,,value_1000_1001_1,value_1000_1001_2,value_1000_1001_1,value_1000_1001_2,value_1000_1001_1,value_1000_1001_2